---
- name: Deploy application
  hosts: app
  become: True
  tasks:

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith # <-- Указываем нужную ветку
    notify: reload puma

  - name: Bundler install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
    notify: reload puma

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
