---
- name: Install MongoDB
  hosts: all
  become: true
  become_user: root
  tasks:

  - name: Install mongodb
    apt:
      name: mongodb
      state: present

  - name: Enable mongodb
    systemd:
      name: mongodb
      enabled: yes
