---
- name: Install Ruby and bundler and git
  hosts: all
  become: True
  become_user: root
  tasks:
  - name: Install Ruby all
    apt:
      name:
      - ruby-full
      - ruby-bundler
      - build-essential
      state: present

  - name: install Git
    apt:
      name: git
      state: present
