#cloud-config
#command for init
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJWf3NUzLCCVyXujbAm6yST62TcuM8wZ4OzN7/RiD9OW koreni@MacBook-Air.local
users:
- name: koreni
  gecos: Admin User
  shell: /bin/bash
  groups: users,admin
  sudo: ALL=(ALL) NOPASSWD:ALL
  lock_passwd: true
  ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJWf3NUzLCCVyXujbAm6yST62TcuM8wZ4OzN7/RiD9OW koreni@MacBook-Air.local
