---
- name: Install Ruby and bundler
  hosts: app
  become: True
  tasks:
  - name: Install Ruby
    apt:
      name: {{ item }}
      status: present
    with_items:
    - ruby-full
    - ruby-bundler
    - build-essential
