---
# you might want to add your own variables here based on what provisioning
# you are doing like:
# image: quay.io/centos/centos:stream8
driver:
  name: vagrant
  provider:
    name: parallels
lint:
  name: yamllint
platforms:
  - name: instance
    box: bento/ubuntu-20.04-arm64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
